# .github/workflows/main.yml

name: IELTS Selenium Bot

on:
  # Allows the workflow to be triggered manually from the Actions tab.
  workflow_dispatch:
  # Runs the workflow on a schedule: every 2 hours.
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # ADDED: Cache webdriver-manager downloads to speed up runs
      - name: 3. Cache webdriver-manager
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: ${{ runner.os }}-wdm-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-wdm-

      - name: 4. Set up Chrome browser and driver
        uses: browser-actions/setup-chrome@v1

      - name: 5. Install Python dependencies
        run: pip install -r requirements.txt

      - name: 6. Run the IELTS Finder Script
        # MODIFIED: Securely passes the secret password as a command-line argument.
        run: python main.py --password ${{ secrets.SENDER_PASSWORD }}
