name: IELTS Selenium Bot

# This allows the workflow to be triggered manually from the Actions tab in GitHub.
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Set up Chrome browser and driver
        uses: browser-actions/setup-chrome@v1

      - name: 4. Install Python dependencies
        run: pip install -r requirements.txt

      - name: 5. Run the IELTS Finder Script
        # This step now runs without the SENDER_PASSWORD environment variable.
        # You must modify main.py to handle the password directly.
        run: python main.py
